// <auto-generated />
using System;
using BankingSystem.WPF.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingSystem.WPF.Db.Migrations
{
    [DbContext(typeof(BankingSystemDbContext))]
    [Migration("20260508212148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingSystem.Core.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BankingSystem.Core.Models.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("BankingSystem.Core.Models.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CashLimit")
                        .HasColumnType("int");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("BankingSystem.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BankingSystem.Core.Models.TransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TransactionRecords");
                });

            modelBuilder.Entity("BankingSystem.Core.Models.SalaryAccount", b =>
                {
                    b.HasBaseType("BankingSystem.Core.Models.Account");

                    b.ToTable("SalaryAccounts", (string)null);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.SavingAccount", b =>
                {
                    b.HasBaseType("BankingSystem.Core.Models.Account");

                    b.ToTable("SavingAccounts", (string)null);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.Account", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Customer", null)
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.Certificate", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Customer", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.CreditCard", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Customer", null)
                        .WithOne("CreditCard")
                        .HasForeignKey("BankingSystem.Core.Models.CreditCard", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.TransactionRecord", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Customer", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BankingSystem.Core.Models.SalaryAccount", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("BankingSystem.Core.Models.SalaryAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingSystem.Core.Models.SavingAccount", b =>
                {
                    b.HasOne("BankingSystem.Core.Models.Account", null)
                        .WithOne()
                        .HasForeignKey("BankingSystem.Core.Models.SavingAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingSystem.Core.Models.Customer", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Certificates");

                    b.Navigation("CreditCard");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
